name: eco_bocado
description: "Applicaci√≥n EcoBocado"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_map: ^7.0.2
  flutter_riverpod: ^3.0.0
  flutter_secure_storage: ^9.2.4
  flutter_stripe: ^11.3.0
  go_router: ^16.2.4
  http: ^1.5.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  qr_flutter: ^4.1.0
  riverpod: ^3.0.0
  shared_preferences: ^2.5.3
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
